/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * Your project description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProject
 */
export interface PatchedProject {
    /**
     * 
     * @type {number}
     * @memberof PatchedProject
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProject
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedProject
     */
    createdByEmail?: string;
}

/**
 * Check if a given object implements the PatchedProject interface.
 */
export function instanceOfPatchedProject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedProjectFromJSON(json: any): PatchedProject {
    return PatchedProjectFromJSONTyped(json, false);
}

export function PatchedProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'createdByEmail': !exists(json, 'created_by_email') ? undefined : json['created_by_email'],
    };
}

export function PatchedProjectToJSON(value?: PatchedProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'created_by_email': value.createdByEmail,
    };
}

